services:
  cakephp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    command: sleep infinity
    networks:
      - db-common-network
    ports:
      - "8765:8765"
    env_file:
      - ./.env

networks:
  db-common-network:
